### ISSUE TITLE
[BUG] Double free cause by mlx_freen when executing mlx_terminate

### ISSUE THREAD

**Issue by bantunesfranco** [codam-coding-college/MLX42#100]
**Describe the bug**
When exiting the program, i call mlx_terminate which is gonna try and deallocate all mlx related memory. When mlx_lstclear is called with mlx_freen as argument to try and free all mlx images it causes a double free.

**To Reproduce**
Im not really sure how to reproduce this. 
It think it has something to do with multiple images using the same allocated pixel buffer pointer.

**Expected behavior**
The program should exit without any problems

**Screenshots**
<img width="1363" alt="Screen Shot 2023-03-31 at 12 43 24 PM" src="https://user-images.githubusercontent.com/94724432/229100331-6768ea07-3fd2-4903-b40d-74e28c4d678f.png">

**Desktop:**
 - OS: MacOS
 - Version: Mojave

**Additional context**
Im allocating the pixel buffers for my animations manually. All the enemies play the same animation at the same time, so they use the same pixel buffer pointer. Im assuming it has something to do with that.

**Comment by W2Wizard** [comment]
Currently a bit busy with other things, sorry for not doing anything about this for 3 Weeks.
If it happens more often to others or if you have been unable to find a work around. I will prioritize it more.

**Comment by Jeroenvh99** [comment]
When every enemy uses the same pointer you'd have to keep track of which pointers you've already free'd to know whether or not a pointer is already free'd by the time you get to that point. What you could do to make this work I think is giving every enemy a pointer to this pixel buffer and then free that buffer once, but I think that requires a bit of a rework of MLX.

**Comment by W2Wizard** [comment]
Closing for now as I have no way to repro this at all
