### ISSUE TITLE
[BUG] mlx_update_matrix ignores passed width and height

### ISSUE THREAD

**Issue by Oktosha** [codam-coding-college/MLX42#107]
**Describe the bug**
The function [mlx_update_matrix](https://github.com/codam-coding-college/MLX42/blob/e143f62f6f88563d5fd9aaf0f517b0b274619573/src/mlx_window.c#L21) ignores its arguments

**To Reproduce**
1. Call mlx_update_matrix with any parameter
2. Don't see any difference

**Expected behavior**
I expect that the function would use its parameters. If the parameters should always be ignored, I expect the function to use local variables instead.

**Additional context**
This is an internal function, so nobody should call it and this bug doesn't matter if mlx42 still works as a whole. But I though it would be nice to let you know anyways, I find it very confusing.

**Comment by W2Wizard** [comment]
Sure, a minor oversight on my end. Thanks for taking the effort :D
