### ISSUE TITLE
[BUG] doesn't work with X11 redirection on Linux VM on MacOS

### ISSUE THREAD

**Issue by Hunam6** [codam-coding-college/MLX42#117]
**Describe the bug**
MLX42 doesn't seem to be working when used with X11 redirection on Linux VM on MacOS.

**To Reproduce**
- Install [XQuartz](https://www.xquartz.org) (`brew install --cask xquartz`)
- Install [Lima](https://github.com/lima-vm/lima) (`brew install lima`)
- Create a new instance (`limactl create bug`)
- Select `Open an editor to review or modify the current configuration`, set those variables to `true`
```yaml
  # Forward X11 into the instance
  # 🟢 Builtin default: false
  forwardX11: true
  # Trust forwarded X11 clients
  # 🟢 Builtin default: false
  forwardX11Trusted: true
```
- Save and launch (`limactl start bug` if necessary)
- `limactl shell bug`
- `cd /tmp/lima`
- Install MLX42 deps (`sudo apt update && sudo apt install build-essential libx11-dev libglfw3-dev libglfw3 xorg-dev cmake -y`)
- [Download and build MLX42](https://github.com/codam-coding-college/MLX42#download-and-build---mlx42)
- `cd ..`
- create a minimal `main.c`
```c
#include "MLX42/include/MLX42/MLX42.h"

int	main(void)
{
	mlx_t	*mlx = mlx_init(512, 512, "MLX42", true);
}
```
- `gcc main.c MLX42/build/libmlx42.a -Iinclude -ldl -lglfw -pthread -lm`
- `./a.out`
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Segmentation fault (core dumped)
```

**Expected behavior**
Nothing because no `mlx_loop` but not errors.
We can check that X11 redirection is working:
- `sudo apt install x11-apps`
- `xeyes`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Sonoma 14.0 (23A344)
 - Device: MacBook Pro M1

**Additional context**
We can remove the first 2 errors using `export LIBGL_ALWAYS_INDIRECT=1`. But I'm not sure if it sweeps the errors under the carpet or if it's really fixing part of the issue.

**Comment by Hunam6** [comment]
Sorry for the delay, I've just checked with this minimal GLFW example and it seems to be working, it opens an empty window.

```c
#include <GLFW/glfw3.h>

int main() {
    if (!glfwInit()) return -1;
    GLFWwindow* window = glfwCreateWindow(640, 480, "Hello, GLFW!", NULL, NULL);
    if (!window) { glfwTerminate(); return -1; }
    glfwMakeContextCurrent(window);
    while (!glfwWindowShouldClose(window)) {
        glfwSwapBuffers(window);
        glfwPollEvents();
    }
    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
```

(I still get these 2 errors so I guess they are not that relevant)
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

**Comment by W2Wizard** [comment]
Ok then it's specifically OpenGL that's struggling here...

**Comment by W2Wizard** [comment]
Closing for now as it's not that important to have unless people REALLY want this I'll put in effort.
Feel free to ping to open the issue again.
