### ISSUE TITLE
All mlx_images_to_window show the same image

### ISSUE THREAD

**Issue by ShroomySquid** [codam-coding-college/MLX42#135]
**Repost from general forum.

Since the last commit (29 march 2024), all of my opened images with the mlx_image_to_window show the same image. The first screenshot show cube3d after the last commit, the second one with the commit of early february. This is on the school mac of Quebec 42 (Catalina).

Any clue what's causing this bug?

<img width="1028" alt="Screen Shot 2024-03-31 at 4 28 06 PM" src="https://github.com/codam-coding-college/MLX42/assets/107887464/f7324388-3df0-4018-b2bd-2f1e65ab4b14">

<img width="1028" alt="Screen Shot 2024-03-31 at 4 30 26 PM" src="https://github.com/codam-coding-college/MLX42/assets/107887464/1826083d-02b1-48b3-a88d-51251bb10e69">

**Comment by W2Wizard** [comment]
Tracking it on #136
