### ISSUE TITLE
MLX last commit failed some unit tests and the project has incorrect rendering

### ISSUE THREAD

**Issue by joeroeg** [codam-coding-college/MLX42#136]
**Describe the bug**
There is a bug how program render minimap and other features in cub3d project

With the latest commit:
commit 5bed5570138fca9d03f7793e7a3ba4eb1c63d907 (HEAD -> master, origin/master, origin/HEAD)
Author: W2Wizard <main@w2wizard.dev>
Date:   Sat Mar 30 02:02:32 2024 +0100

**The program is rendering the data incorrectly. We cannot not see:**
- a minimap
- fps monitor
- center aim

<img width="1028" alt="no_map" src="https://github.com/codam-coding-college/MLX42/assets/21306729/d9fb69d3-991c-43b7-96b2-c080f7b7fd51">

-------------------------------------------------------------------------------------------

**but when i switch to this commit:**
commit f87c401e495dcf56e9162a2241d7761238bb189f (HEAD)
Author: W2Wizard <main@w2wizard.dev>
Date:   Fri Mar 29 15:33:14 2024 +0100

**or even this commit**
commit 5e826c2390e83a3acf175fef9b42d4b52cb38ae9 (HEAD)
Author: W2Wizard <main@w2wizard.dev>
Date:   Wed Feb 28 12:49:56 2024 +0100

**the program is rendering the image correctly. We can see:**
- a minimap
- fps monitor
- center aim

<img width="1028" alt="yes_map" src="https://github.com/codam-coding-college/MLX42/assets/21306729/30e0f866-0646-40c1-9c2d-148ce773677f">

-------------------------------------------------------------------------------------------
**To Reproduce**
1. Go to and dowload the project https://github.com/ShroomySquid/Cub3D
2. Compile: make
3. Run a game: ./cub3d ./maps/valid_map.cub
4. See an error

**Desktop**
 - OS: MacOS
 - Version: Catalina 10.15.7

**Comment by W2Wizard** [comment]
Oopsie! Seems like I pushed and didn't check the tests 😂

Will fix it soon!

**Comment by W2Wizard** [comment]
For future reference you might want to stick to specific releases instead of upstream.

E.G: `git clone --depth 1 --branch <tag_name> <repo_url>`

**Comment by joeroeg** [comment]
Yes, everything is working as it should.
