### ISSUE TITLE
[BUG] Failed to create window on MacOS

### ISSUE THREAD

**Issue by flomero** [codam-coding-college/MLX42#143]
**Describe the bug**
v2.4.0 doesn't work on MacOS. calling `mlx_init` returns `NULL` and `mlx_errno` is set to "_Failed to create window_".

this bug was introduced with the release of v2.4.0, earlier versions work fine.

after looking into it, i think it's caused by the deletion of the following line [here](https://github.com/codam-coding-college/MLX42/commit/7a0d6f8f0a2df84f01a9c55b412c349b05565058#diff-402abf74dc11c0c4e9664c85a683b3df64bc569bdf7421b65cfb544dc252ee38L187) in #142 

```c
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
``` 

adding that back in fixes the issue

**Desktop:**
 - OS: MacOS
 - Version: Catalina 10.15.7

**Comment by W2Wizard** [comment]
Oof! That's weird, thought the tests would fail guess not? Let me fix this super fast.

**Comment by W2Wizard** [comment]
Weirdly enough at least on my M3, it worked before as well. I don't have a catalina mac availble to me atm.

<img width="542" alt="image" src="https://github.com/user-attachments/assets/2fbc5ab5-2207-408f-916f-48b66ed03833">

**Comment by flomero** [comment]
Master works now, thanks :D
we are still using Catalina Macs in Heilbronn Campus (but soon™️  switching to Linux)
