### ISSUE TITLE
[REQUEST] Add ability to scale images with window size. 

### ISSUE THREAD

**Issue by Raspurrin** [codam-coding-college/MLX42#27]
There is no way to resize an image when the window gets resized.
If you comment out line 68 this effect can be achieved, but it would be better to have it as an option somewhere:
https://github.com/codam-coding-college/MLX42/blob/0103a86db929f358201ad25d8ddf8bb776b9a1ac/src/mlx_init.c#L67-L69

**Comment by W2Wizard** [comment]
Added with https://github.com/codam-coding-college/MLX42/commit/facef0d894c7cce731c5a34e3f551814fc96dafc

In `MLX42.h` you can now find global variable settings that you need to set (or not if you use their default values) to change certain aspects of mlx's behaviour.

In the future if new things come up I can easily expand and add new settings without changing the API too much. Enjoy.

<img width="777" alt="Screen Shot 2022-04-20 at 9 53 45 AM" src="https://user-images.githubusercontent.com/63303990/164178861-5468e396-177a-41db-a4e4-57536b3ee129.png">
