### ISSUE TITLE
[BUG] Recursive Make calls not working

### ISSUE THREAD

**Issue by willaCS** [codam-coding-college/MLX42#58]
**NOTE**
I was trying to setup your library (Great Job btw) on my project but in didnt work compile with the recursive call of make (Make -C folder/).

**Describe the bug**
The command "Make -C" with the library return highly inconsistent result. Either not compiling every file or trying to compile file in folder ending in .c which does not work. And Make -C fclean does the same

**To Reproduce**
1. Clone the library
2. Execute "Make -C MLX42"
3. Execute "Make -C MLX42 fclean"
4. Repeat multiple times 2 and 3 to see the inconsistencies.

**Expected behavior**
"Make -C MLX42" will not compile every file each times. It will either only compile the shader files (alias frag_shader and vert_shader) or all files.
<img width="1013" alt="Make" src="https://user-images.githubusercontent.com/80853886/194277844-47852692-6de5-4b85-a5a4-0e1dc26c205c.png">

"Make -C MLX42 fclean" will delete everyfile but sometimes it will try to delete "src/mlx_cursor.c/mlx_font.o" for example which will not work.
<img width="1013" alt="Make_fclean" src="https://user-images.githubusercontent.com/80853886/194277862-0068af33-4e46-4ec5-8498-b148d2de589e.png">

**Desktop (please complete the following information):**
 - MacOS Catalina 10.15.7

**Comment by willaCS** [comment]
I speculate it has to do with the wildcare inside the makefile i'm no makefile expert.

**Comment by W2Wizard** [comment]
Weirdly enough I can't reproduce this? Tried on MacOS Ventura 13.0 (Beta), after like 10 tries this never happens to me.

Don't really know what to say here as I've never witnessed this nor has anyone else ever reported this issue to me prior.

**Comment by willaCS** [comment]
sorry for the late response, i tried it again on mac in Brussels but yet again i have the same problem.
I will try on another pc again.
<img width="650" alt="Screen Shot 2022-10-10 at 8 56 16 AM" src="https://user-images.githubusercontent.com/80853886/194812273-5658c777-1f8b-4382-afbb-f041fce5796b.png">

**Comment by willaCS** [comment]
Other pc here, still the same look
<img width="740" alt="Screen Shot 2022-10-10 at 9 01 18 AM" src="https://user-images.githubusercontent.com/80853886/194813268-10c6258f-2d09-4883-adeb-ffdcec1d577f.png">
If its an issue, its only mac 10.15.7.
I'll look more into it.


It's annoying because it means I can't use your lib on pc in my school.

**Comment by W2Wizard** [comment]
This time I ran it on our Macs at Codam, they are on MacOS 10.14.6.
It still works on my end 😕?

Actually if you want a fix you could try removing the recursive stuff and make it work in the 'traditional way' in the lib's makefile and see if that fixes your issues, if it does I can look into switching out the entire build system to `cmake` instead maybe.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/63303990/194819650-83c7999d-10dd-4f60-9bf9-856242cfbd17.png">

**Comment by willaCS** [comment]
I was trying to compile it once inside the folder but it didnt work that time (?!?)
<img width="655" alt="Screen Shot 2022-10-10 at 9 22 34 AM" src="https://user-images.githubusercontent.com/80853886/194821745-8e984d7b-0d3e-4638-a239-b34c5a3ef780.png">

I tried looking at where the rule didnt work and your rwildcard function and tried to print the result.
Observation: only mlx_font.o/.c seems to bug somehow

i found out that the secund wildcard is the one that send the erroneous mlx_font.o
`rwildcard = $(subst \,/,$(sort $(foreach d,$(wildcard $1/*),$(call rwildcard,$d,$2) $(wildcard $1/$2))))
____________________________________________^^^^^^^^`

so i replaced the argument with $1/*.c and it seems to work for now

**Comment by willaCS** [comment]
> look

`GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

`

**Comment by willaCS** [comment]
Final post of the day (I need to work on my projects)
I tried switching to $(shell find ...) which i assume you didnt use for windows users but i tried anyway.
and it is more consistent but in bad because it need two make to fully compile.
<img width="655" alt="Screen Shot 2022-10-10 at 10 46 30 AM" src="https://user-images.githubusercontent.com/80853886/194828971-4ad163f1-4469-4097-9d42-1f6e1e8d5077.png">

I really need to upgrade my make knowledge.

**Comment by W2Wizard** [comment]
Ok well this is maybe more than reason enough to update the build system.
I already did an attempt at it once but I need finish it basically, then this shouldn't happen later.

Thanks for letting me know, I can only suggest you replace all the recursive function calls with the `shell find` instead for now.

**Comment by W2Wizard** [comment]
Trying to see if I can fix this for 2.3.0.

The plan is to remove Windows entirely and instruct people to use WSL2 if they want the easy way of running their programs with this lib. Alternatively they can write a native Windows version if they dare to.

You can track the progress on the `cmake` branch which I aim to merge to master at some point.
