### ISSUE TITLE
Readme not reflecting CMake

### ISSUE THREAD

**Issue by JellevanKraaij** [codam-coding-college/MLX42#79]
There is no CMake documentation for Linux and mac in the readme.
Please add examples on how to compile it and add some documentation on how to integrate it with a normal Makefile.
With kind regards
@JellevanKraaij  & @Abdi-29

**Comment by W2Wizard** [comment]
I mean: https://github.com/codam-coding-college/MLX42/blob/master/docs/Basics.md

**Comment by JellevanKraaij** [comment]
Me and Abi confused that the documentation on how to install is below the example of MacOS & Linux, i totally overlooked that part where it showed how to run CMake

Maybe we can change the order so the git clone & cmake is documented before the MacOS & Windows section.
I will make a pull request soon

BTW i love that you made CMake work!!!!
