### ISSUE TITLE
[BUG] Shader build process executing incorrectly

### ISSUE THREAD

**Issue by bantunesfranco** [codam-coding-college/MLX42#91]
**Describe the bug**
Cmake builds MLX42  incorrectly when a folder name contains a space character.

**To Reproduce**
1. mkdir [name] - Make sure name contains a space. Ex: "test test"
2. cd [name]
3. git clone https://github.com/codam-coding-college/MLX42.git
4. cd MLX42
5. cmake -B build 
6. cmake --build build -j4  or do make -C build -j4

**Expected behavior**
MLX42 should be built without any issues.

**Screenshots**
<img width="1193" alt="Screen Shot 2023-02-24 at 12 14 43 PM" src="https://user-images.githubusercontent.com/94724432/221166211-cefcfbbe-e10f-4ebe-8dc5-310b68f74f4a.png">

<img width="806" alt="Screen Shot 2023-02-24 at 12 34 43 PM" src="https://user-images.githubusercontent.com/94724432/221169461-c27cff98-2ccb-4a2c-8ab8-266e9e697f03.png">

Should contain const char* frag_shader = "#version 330 core\n" instead of const char* frag_shader = "\n"

**Additional context**
Apparently Cmake sees dir "test test" as 2 different directories, so when it tries to compile the shaders it can't find the files because it doesn't find the correct folder . (See screenshot)
MLX42 still gets built, but when you try to execute any code that uses the library its gives a version missing error. (See second screenshot)

**Comment by W2Wizard** [comment]
Aha! You found a way to reproduce it! I remember it being weird that only you had this issue but doing those steps I get the exact same behaviour.

Will look into it, thank you 👍

**Comment by JellevanKraaij** [comment]
Created PR to solve this issue #92
