### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lacusch** [codam-coding-college/MLX42#95]
**Describe the bug**
 `git submodule update --init --recursive --remote` can't run as there is no `.gitmodules` for `googletest-src`

**To Reproduce**
1. Init a new git repository
2. Add MLX as a submodule
3. `Run git submodule update --init --recursive --remote`

**Expected behavior**
MLX compiles without a problem, as it has done before.

**Screenshots**
<img width="2560" alt="Screen Shot 2023-03-03 at 10 50 43 AM" src="https://user-images.githubusercontent.com/68818166/222688675-0b969f0f-5af5-49f9-bd7e-6332fa8e81a6.png">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Version: [Catalina], Version 10.15.7 (19H1715)

**Additional context**
My tip would be that the broken chage is with Pull request #94, but I'm not sure

**Comment by JellevanKraaij** [comment]
Will look into it later this day.
I accidentally committed gtest dep, will revert it.
Maybe _deps is not part of .gitignore?

**Comment by Lacusch** [comment]
Thanks for the quick reply I agree that could be the case

**Comment by JellevanKraaij** [comment]
Already fixed it, now we wait on @W2Wizard to merge PR #96
I somehow managed to add a _deps folder :astonished:

**Comment by Lacusch** [comment]
Nice thanks for the quick fix, I'll close the issue once your fix is merged

**Comment by JellevanKraaij** [comment]
It should be closed automatically when my commit is merged

**Comment by W2Wizard** [comment]
Done and Done ✅
